### ISSUE TITLE
如何在 langchain 中调用 DeepSeek-V2？

### ISSUE THREAD

**Issue by soloice** [deepseek-ai/DeepSeek-V2#18]

**Comment by soloice** [comment]
有些用户问到怎么在 langchain 里调用 DeepSeek-V2，由于我们的接口和 OpenAI 完全兼容，所以可以直接使用 OpenAI 接口，换一下模型名称、url 和 key 即可，如下所示：

```
from langchain_openai import ChatOpenAI
llm = ChatOpenAI(
        model='deepseek-chat', 
        openai_api_key=<your-deepseek-api-key>, 
        openai_api_base='https://api.deepseek.com/v1', 
        temperature=0.85, 
        max_tokens=8000
        )
```

**Comment by CarlQAQ** [comment]
不行的，ChatOpenAI方法没有像你这种参数model='deepseek-chat', 
        openai_api_key=<your-deepseek-api-key>, 
        openai_api_base='https://api.deepseek.com/v1',

**Comment by ZhangJiaQ** [comment]
从这个地方Import 就有了 @CarlQAQ 

from langchain_openai import ChatOpenAI

**Comment by SyJarvis** [comment]
pip install langchain-deepseek

from langchain_deepseek import ChatDeepSeekAI
from langchain_core.output_parsers import StrOutputParser

llm = ChatDeepSeekAI(
    model="deepseek-chat",
    api_key="sk-...",
)

output_parser = StrOutputParser()
chain = llm | output_parser
response = chain.invoke("太阳系有几大行星？")
print(response)
