### ISSUE TITLE
代码开源相关

### ISSUE THREAD

**Issue by DXZDXZ** [deepseek-ai/DeepSeek-V2#22]
请问 Aux Loss 部分的 device-level balance loss 和 communication balance loss 代码会开源吗，还有后面的 Token Dropping 策略

**Comment by luofuli** [comment]
暂无开源计划
---- 回复的原邮件 ----
***@***.***>发送日期2024年05月11日 18:09 ***@***.***> ***@***.***>主题[deepseek-ai/DeepSeek-V2] 代码开源相关 (Issue #22)
请问 Aux Loss 部分的 device-level balance loss 和 communication balance loss 代码会开源吗，还有后面的 Token Dropping 策略
