### ISSUE TITLE
Device-Level Balance Loss and Communication Balance Loss

### ISSUE THREAD

**Issue by hsm1997** [deepseek-ai/DeepSeek-V2#25]
What's the main difference?
As I see from your paper, pi' == pi'', and fi' = some_coeff * fi''
maybe fi'' should be:
... (Token t is sent to Device i from Device j where j!=i)

**Comment by hsm1997** [comment]
maybe the authors already meant this by using the word "sent"...

**Comment by tianzhangwu** [comment]
solved my puzzle
