### ISSUE TITLE
128k的推理有例子吗？

### ISSUE THREAD

**Issue by 520jefferson** [deepseek-ai/DeepSeek-V2#56]
如何通过32k扩展到128k，有例子或者脚本吗？ 8卡 a100 80G*8能推理128k吗？

**Comment by 520jefferson** [comment]
我看huggingface那个的配置文件就有yarn，最大长度130w，但是输入超过32k后，返回结果为空啊

**Comment by 520jefferson** [comment]
vllm输入长度设置为100k报错了：

**Comment by ybdesire** [comment]
@520jefferson 请问您max_model_len最长能设置为多大呢？

**Comment by 520jefferson** [comment]
> @520jefferson 请问您max_model_len最长能设置为多大呢？

32k，100k需要int4 量化和kv cache优化
