### ISSUE TITLE
希望做vs2022扩展

### ISSUE THREAD

**Issue by woaidianqian** [deepseek-ai/DeepSeek-V2#68]
vscode上已经有了continue，效果甚至超越github copilot。
codegeex，tongyilingma，同时支持vscode和vs2022，都深度体验过，目前很拉胯。
迫切希望开发一个visual studio上的扩展插件，编码能力绝对领先。

**Comment by maybgit** [comment]
我也强烈有这个需求，vscode与vs都在用，目前vs用着continue，配置的是deepseek，vs2022没有类似的插件，想用deepseek都用不了。

**Comment by huangshixian2023** [comment]
啥时候出插件试试

**Comment by 1amCaptain** [comment]
几时在vs2022出个扩展啊,很需要呀

**Comment by suyiming** [comment]
几时在vs2022出个扩展啊,很需要呀

**Comment by Veloctor** [comment]
几时在vs2022出个扩展啊,很需要呀
