### ISSUE TITLE
API ERROR

### ISSUE THREAD

**Issue by 851039536** [deepseek-ai/DeepSeek-V2#9]
"detail": "Invalid top_logprobs and logprobs value"

**Comment by CoruNethron** [comment]
Same here. Even with example curl request from the API docs page.

**Comment by mutse** [comment]
Same here. Error:  [Error: 401 Authentication Fails (no such user)

**Comment by DillionApple** [comment]
The error `"detail": "Invalid top_logprobs and logprobs value"` is because when you set `top_logprobs`, you MUST set `logprobs` to True. The default value of these two parameters is wrong in the api-doc. We have fixed them. @851039536 @CoruNethron
